//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleBot {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42")]
        public string GitToken {
            get {
                return ((string)(this["GitToken"]));
            }
            set {
                this["GitToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ws://10.0.0.2:4455")]
        public string ObsWebsocketUrl {
            get {
                return ((string)(this["ObsWebsocketUrl"]));
            }
            set {
                this["ObsWebsocketUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ObsWebsocketPassword {
            get {
                return ((string)(this["ObsWebsocketPassword"]));
            }
            set {
                this["ObsWebsocketPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a4lltinre0n377a7l8mb4pd3g2odym")]
        public string TwitchClientId {
            get {
                return ((string)(this["TwitchClientId"]));
            }
            set {
                this["TwitchClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SimpieBot")]
        public string TwitchBotUsername {
            get {
                return ((string)(this["TwitchBotUsername"]));
            }
            set {
                this["TwitchBotUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\SimpleVar\\Desktop\\oauth_simpiebot")]
        public string TwitchOAuthBot {
            get {
                return ((string)(this["TwitchOAuthBot"]));
            }
            set {
                this["TwitchOAuthBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\SimpleVar\\Desktop\\oauth_simplevar")]
        public string TwitchOAuth {
            get {
                return ((string)(this["TwitchOAuth"]));
            }
            set {
                this["TwitchOAuth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\SimpleVar\\Desktop\\SimpleBot user data")]
        public string UserDataFolder {
            get {
                return ((string)(this["UserDataFolder"]));
            }
            set {
                this["UserDataFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SimpleVar")]
        public string Channel {
            get {
                return ((string)(this["Channel"]));
            }
            set {
                this["Channel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!")]
        public string CommandsPrefix {
            get {
                return ((string)(this["CommandsPrefix"]));
            }
            set {
                this["CommandsPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SneakyJapanRound {
            get {
                return ((string)(this["SneakyJapanRound"]));
            }
            set {
                this["SneakyJapanRound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_all_SimpleVar_systems {
            get {
                return ((bool)(this["enable_all_SimpleVar_systems"]));
            }
            set {
                this["enable_all_SimpleVar_systems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool obs_enabled {
            get {
                return ((bool)(this["obs_enabled"]));
            }
            set {
                this["obs_enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool active_window_tracking_enabled {
            get {
                return ((bool)(this["active_window_tracking_enabled"]));
            }
            set {
                this["active_window_tracking_enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int SR_minDuration_inSeconds {
            get {
                return ((int)(this["SR_minDuration_inSeconds"]));
            }
            set {
                this["SR_minDuration_inSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5400")]
        public int SR_maxDuration_inSeconds {
            get {
                return ((int)(this["SR_maxDuration_inSeconds"]));
            }
            set {
                this["SR_maxDuration_inSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SR_maxSongsInQueuePerUser {
            get {
                return ((int)(this["SR_maxSongsInQueuePerUser"]));
            }
            set {
                this["SR_maxSongsInQueuePerUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int SR_maxVolume {
            get {
                return ((int)(this["SR_maxVolume"]));
            }
            set {
                this["SR_maxVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int SR_volume {
            get {
                return ((int)(this["SR_volume"]));
            }
            set {
                this["SR_volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MaxFollowGreetingsPerEveryFewSeconds_negativeMeansNoLimit {
            get {
                return ((int)(this["MaxFollowGreetingsPerEveryFewSeconds_negativeMeansNoLimit"]));
            }
            set {
                this["MaxFollowGreetingsPerEveryFewSeconds_negativeMeansNoLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LastMainFormPosition {
            get {
                return ((global::System.Drawing.Point)(this["LastMainFormPosition"]));
            }
            set {
                this["LastMainFormPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size LastMainFormSize {
            get {
                return ((global::System.Drawing.Size)(this["LastMainFormSize"]));
            }
            set {
                this["LastMainFormSize"] = value;
            }
        }
    }
}
